FROM nixos/nix:2.35.1@sha256:377d4887aca98f0dfa12971c1ea6d6a625a435d8b610d4c95a436843da6fbfd1

ENV NIX_CONFIG="experimental-features = nix-command flakes"
WORKDIR /workspace

CMD ["sleep", "infinity"]
