[package]
name = "cinnabar"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0 WITH LLVM-exception"
default-run = "cinnabar"

[lib]
name = "cinnabar"
path = "src/lib.rs"

[[bin]]
name = "cinnabar"
path = "src/main.rs"

[[bin]]
name = "cinnabar-lsp"
path = "src/bin/cinnabar_lsp.rs"

[features]
test-profile-balanced = []
test-profile-smoke = []

[dependencies]
ariadne = "0.6.0"
clap = "4.6.5"
inkwell = { version = "0.9.0", features = ["llvm21-1"] }
lsp-server = "0.7"
serde_json = "1"

[lints.rust]
warnings = "deny"
dead_code = "deny"
non_snake_case = "deny"
non_upper_case_globals = "deny"
non_camel_case_types = "deny"
unused_variables = "deny"
unused_imports = "forbid"
unused_must_use = "forbid"
unreachable_patterns = "forbid"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"
wildcard_enum_match_arm = "deny"
match_wildcard_for_single_variants = "deny"
match_wild_err_arm = "deny"
rest_pat_in_fully_bound_structs = "deny"
ignored_unit_patterns = "deny"
